### ISSUE TITLE
Test stuck at send_raw_transaction

### ISSUE THREAD

**Issue by manxiaqu** [tomusdrw/rust-web3#416]
The test code is stuck at send_raw_transaction, it seems the rpc request isn't actually send to my local node, I didn't say any request info from console:
```rust
#[tokio::test]
    async fn send_raw() {
        // Ganache-cli already started.
        let transport = web3::transports::Http::new("http://localhost:8545").unwrap();
        use web3::api::Eth;
        use web3::types::Bytes;

        // send raw transaction
        let eth = Eth::new(transport);
        let result = eth.send_raw_transaction(Bytes(vec![]));
        // stuck at this!!!!
        futures::executor::block_on(result).unwrap();
    }
```
But it works fine that calling send_raw_transaction at tokio main function in example.
```rust
#[tokio::main]
async fn main() -> web3::Result<()> {
// code omitted
}
```
Am I miss something Or misconfigure something?

cargo.toml
```toml
[package]
name = "rect"
version = "0.1.0"
edition = "2018"


[dependencies]
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
tokio = { version = "0.2", optional = true, features = ["full"] }
secp256k1 = { version = "0.19", features = ["recovery"] }
futures = "0.3.5"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
```
